name: deploying
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploying 
              uses: actions/checkout@v4
            - name: uploading artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./
            - name: dowloading distro
              uses: actions/deploy-pages@v4